name: Python application with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t pyapp .

    - name: Run Docker container
      run: docker run --name test_container pyapp

    - name: Copy test results from container
      run: docker cp test_container:/app/test-reports/ ./test-reports

    - name: Cleanup
      run: docker rm -f test_container

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: unittest-results
        path: ./test-reports/
